### ISSUE TITLE
Not able to see March reviews although March review progress is 101%

### ISSUE THREAD

**Issue by Jivnesh** [acl-org/arr-health#13]
On the ARR stats page for the March cycle, it shows that all the papers have been reviewed (101% progress) and 12% of the papers are remaining to get meta-reviews. However, I am not able to see the remaining reviews for my March submission.

Is it that all the reviews will be revealed after the completion of the meta-reviewing process? Or is there some technical glitch in openreview? Or there is some bug while showing the progress on reviews?

**Comment by jkkummerfeld** [comment]
Hopefully this was resolved, apologies for the delayed response here.

For future readers seeing this issue, please send these types of questions to the ARR support email address (see https://aclrollingreview.org/people).
