### ISSUE TITLE
Fix meta review and notification deadlines for January 2022

### ISSUE THREAD

**Issue by habernal** [acl-org/arr-health#6]
http://stats.aclrollingreview.org/january/

> Meta Review Deadline: 20 Feb 2022
> Earliest Notification: 21 Feb 2022

I think these were adjusted by ARR/NAACL editors in their e-mail:

> [Friday Feb 18 - Tuesday Feb 22, 2022] - Emergency reviewing
> [Wednesday Feb 23 - Saturday Feb 26, 2022] - AEs lead discussion if needed and write meta-reviews
> [Sunday February 27, 2022] - Reviews and meta-reviews released to the authors

(sidenote: super cool project!!! :)

**Comment by SebastinSanty** [comment]
Thank you @habernal for reporting this issue! I have made the changes (which will get reflected in the next daily update) :)

**Comment by SebastinSanty** [comment]
This is live now so closing the issue. Thanks again!
